Fixed typos and restored the semantic forms
NotDotTeam/trust pull request #14
Opened 2018-04-09 14:05 UTC by bopoh13

+ BOM was deleted at the files with encoding of UTF-8

2018-04-09 14:12 UTC, bopoh13 commented
Fixed #13 in lines 643-645 of the file "words.html"

2018-04-09 14:13 UTC, toby3d commented on words.html
> -<i>Обезьяний робот! Ниндзя тако пицца! Лол я такой непредсказуемый</i><br>
Думаю здесь всё-таки лучше оставить `Лол`, как насмешку персонажа над самим собой.

2018-04-09 14:13 UTC, toby3d commented
Спасибо за PR!
Пожалуйста, убедитесь что весь текст всё ещё умещается в предназначеном для него пространствах. Если это не так - сократите проблемные блоки текста.

2018-04-09 14:14 UTC, toby3d commented on notes/index.html
> +<p>В повторяющейся игре на доверие (также известной как <em>Итерационной Дилемме Заключённого</em>) важно, чтобы ни один из игроков не знал, <em>когда</em> последний раунд. Зачем? Подумайте об этом -
Не совсем ясно в чём заключаются изменения. :thinking:

2018-04-09 14:15 UTC, bopoh13 commented on notes/index.html
> +<p>В повторяющейся игре на доверие (также известной как <em>Итерационной Дилемме Заключённого</em>) важно, чтобы ни один из игроков не знал, <em>когда</em> последний раунд. Зачем? Подумайте об этом -
Частица "во" была не к месту. Исправил на "в предпоследнем раунде".

2018-04-09 14:15 UTC, toby3d commented on words.html
> +<br><br>
Есть вероятность что эти переносы сломают визуальное представление текста, например заставив уехать за другие элементы. Надо проверить.

2018-04-09 14:16 UTC, toby3d commented on notes/index.html
> +<p>В повторяющейся игре на доверие (также известной как <em>Итерационной Дилемме Заключённого</em>) важно, чтобы ни один из игроков не знал, <em>когда</em> последний раунд. Зачем? Подумайте об этом -
Да, вижу. Вопрос снят.

2018-04-09 14:16 UTC, bopoh13 commented on words.html
> +<br><br>
Я проверил: не сломают. У блока достаточно ещё места.

2018-04-09 14:26 UTC, bopoh13 commented on words.html
> -<i>Обезьяний робот! Ниндзя тако пицца! Лол я такой непредсказуемый</i><br>
Вернул как было.

2018-04-09 14:44 UTC, bopoh13 commented
Так, похоже я не удалил BOM, а насорил ими. :smirk_cat: Придётся сделать ещё 2 коммита.

2018-04-09 17:26 UTC, Minoru requested changes

2018-04-09 17:26 UTC, Minoru commented on words.html
> +Теория игр на этот счёт имеет две идеи:
Мне кажется, по-русски так не говорят. Читается, как калька с английского. Можно пояснить мотивацию этого изменения?

2018-04-09 17:26 UTC, Minoru commented on words.html
> +Если ты обманешь, я сжульничаю <i>в свой следующий ход</i>, даже если твой ход, вероятно, был ошибкой.
Примитизированный язык здесь не зря; таким образом обыгрывается название персонажа. В оригинале так же. Считаю, что это изменение нужно откатить.

2018-04-09 17:26 UTC, Minoru commented on words.html
> +<br><br>
Подтвержаю: там в левой части экрана большая картинка, а справа совсем чуток текста. Парочка переводов строк ничего не сломают.

2018-04-09 18:01 UTC, bopoh13 commented on words.html
> +Теория игр на этот счёт имеет две идеи:
В данном случае мотивацией является только читаемость текста под кнопкой #13 на странице.

2018-04-09 18:05 UTC, bopoh13 commented on words.html
> +Если ты обманешь, я сжульничаю <i>в свой следующий ход</i>, даже если твой ход, вероятно, был ошибкой.
Возможно, данный диалект является частью игры. Но чтобы понять правила, которым подчиняется данный персонаж, мне потребовалось несколько итераций. Могу изменить текст под диалект, например, реднеков или гопников.

2018-04-09 18:20 UTC, Minoru commented on words.html
> +Теория игр на этот счёт имеет две идеи:
Не понимаю, о какой кнопке речь. Вот что я вижу на этой страничке: 
![screenshot-2018-4-9](https://user-images.githubusercontent.com/118875/38515070-c05179cc-3c3b-11e8-9dc5-3ac3adc4095e.png)

Какая кнопка имеется в виду?

2018-04-09 18:22 UTC, Minoru commented on words.html
> +Если ты обманешь, я сжульничаю <i>в свой следующий ход</i>, даже если твой ход, вероятно, был ошибкой.
Речь школьника или даже ребёнка здесь была бы к месту, можно попробовать. (Но я не представляю, как это будет выглядеть — т.е. сам написать не могу :)

2018-04-09 18:26 UTC, bopoh13 commented on words.html
> +Если ты обманешь, я сжульничаю <i>в свой следующий ход</i>, даже если твой ход, вероятно, был ошибкой.
"Двоечники" пишут с ошибками в элементарных правилах без знаков препинания :)

2018-04-09 18:26 UTC, bopoh13 commented on words.html
> +Теория игр на этот счёт имеет две идеи:
1. https://screenshots.firefox.com/aFLXoIMOo67qJZNX/notdotteam.github.io
2. https://screenshots.firefox.com/UABAmrVX6hpRtqow/notdotteam.github.io

2018-04-09 18:59 UTC, Minoru commented on words.html
> +Теория игр на этот счёт имеет две идеи:
М, понятно. Я бы просто убрал слово «сильные». @toby3d, что думаешь на этот счёт?

2018-04-09 19:01 UTC, toby3d commented on words.html
> +Теория игр на этот счёт имеет две идеи:
@Minoru Соглашусь. Думаю мы не много потеряем отбросив одно слово.

2018-04-09 19:03 UTC, toby3d commented on words.html
> +Если ты обманешь, я сжульничаю <i>в свой следующий ход</i>, даже если твой ход, вероятно, был ошибкой.
Персонаж - "простак". То есть надо обыграть его примитивное мышление и очень упрощённую речь. Либо это чувак с деревни, либо двоечник или что-то вроде.

2018-04-09 19:06 UTC, Minoru commented on words.html
> +Если ты обманешь, я сжульничаю <i>в свой следующий ход</i>, даже если твой ход, вероятно, был ошибкой.
GitHub не присылает уведомления о правке комментариев, так что твои правки выше не сразу бросились в глаза; извини.

Мне не нравится подмена смысла в «я отдам тебе монету» и «даже если это ошибка»:

1. игроки отдают монеты какой-то машине, а не друг другу;
2. в исходнике речь шла про ошибку противника, а в предлагаемой версии речь уже об ошибке Простака.

Также не уверен, что ошибка всего лишь в двух словах достаточно хорошо передаёт смысл персонажа.

@bopoh13, а ты читал англоязычный исходник? Может, удастся оттуда почерпнуть вдохновения?

2018-04-09 19:13 UTC, bopoh13 commented on words.html
> +Если ты обманешь, я сжульничаю <i>в свой следующий ход</i>, даже если твой ход, вероятно, был ошибкой.
Да, согласен. Присутствует двусмысленность. Оригинал не читал; попробую составить другой вариант.

2018-04-10 12:32 UTC, bopoh13 commented on words.html
> +Если ты обманешь, я сжульничаю <i>в свой следующий ход</i>, даже если твой ход, вероятно, был ошибкой.
У детей в устной речи возникают ошибки, которые перетекают в дисграфию. Неправильное спряжение глаголов не самый частый вариант, но и не самый путанный. Добавлю грамматических ошибок. Заменить фразу "если это ошибка" не могу.
> превет. сначала я доверять тебе.
если ты тоже доверять мене, я повторять <i>свой ход</i>, даже если это ошибка.
если ты обмануть меня, я делать <i>свой ход наоборот</i>, даже если это ошибка.

2018-04-10 12:46 UTC, toby3d commented on words.html
> +Если ты обманешь, я сжульничаю <i>в свой следующий ход</i>, даже если твой ход, вероятно, был ошибкой.
Может заменить `даже если __это__ ошибка` на `даже если __была__ ошибка`? :thinking: 

**P.S.:** стольким графоманством занимаемся, хоспаде. х)

2018-04-10 17:16 UTC, Minoru commented on words.html
> +Если ты обманешь, я сжульничаю <i>в свой следующий ход</i>, даже если твой ход, вероятно, был ошибкой.
Хм, а ведь в оригинале было так:

> if you cooperate back, i do *same thing* as last move, even if it mistake.

То есть непонятно, про текущий ход речь или про предыдущий, но зато совершенно ясно, что Простак говорит о *своём* ходе, а не ходе противника. Я выше был неправ, пардон.

Мне нравится последний вариант, предложенный @bopoh13 в комментарии. Предлагаю оставить его.

2018-04-11 08:15 UTC, bopoh13 commented
Проверьте, пожалуйста, перенос строк в файле 'crlf' или 'lf"? Много изменений получилось.

2018-04-11 08:26 UTC, toby3d commented
@bopoh13 Смотрю последние изменения и не понял почему теперь каждый блок засвечен как подвергнувшийся правкам.

ИМХО: Переносы строк между блоками не важны. Они скорее для читаемости исходного кода.

2018-04-11 08:46 UTC, bopoh13 commented
@toby3d, всё-таки в _*nix_-ах и _Windows_ разные символы переноса строк. Избавится от пробелов при просмотре можно добавив `?w=1`, а вот о символах переноса строки ничего не нашёл.
У GitHub файлы должны храниться как в _*nix_-ах. Похоже, мои фильтры работают не корректно.

2018-04-11 16:12 UTC, Minoru requested changes

2018-04-11 16:12 UTC, Minoru commented on words.html
> +Ну да, это кажется правильным... <b>ИЛИ НЕТ!?</b>
[В оригинале](https://github.com/ncase/trust/blob/1cee99ea9800cc7f1084ff50efddcc527f83107a/words.html#L188) два вопросительных знака:

> Sure, seems like the right thing to do... <b>OR IS IT??</b>

2018-04-11 16:36 UTC, Minoru approved these changes

2018-04-11 16:37 UTC, Minoru commented
LGTM. Спасибо!

2018-04-11 16:43 UTC, merged

2018-04-11 16:45 UTC, bopoh13 commented
Спасибо. Я тоже рад, что мы договорились )

2018-07-27 14:46 UTC, bopoh13 commented
**[Заметка]** Причины нежелательного изменения строк и методы устранения ошибки:
1. Все блоки в файле - стандартный текстовый редактор Windows перед символом-LF конца строки ставит символ-CR возврата каретки.  
= Можно удалить перед индексацией:
``` bash
find . -type f \( -name "*.html" -o -name "*.js" -o -name "*.liquid" -o -name "*.md" \) -print0\
 | xargs -0 grep -m1 -l `printf "^\xEF\xBB\xBF"` | xargs sed -i "1 s/^\xEF\xBB\xBF//; s/\$/\x0D/"\
 && git ls-files -mo --eol
```
2. Отдельные не англоязычные блоки - изменилась кодировка файла.  
= Следует проверить фильтры в `.gitattributes`. Можно ыывести `git ls-files --eol` окончания строк в файлах репозитория (слева) и на локальной машине (справа).

2018-07-27 18:03 UTC, Minoru commented
По первому пункту у Git уже есть готовая настроечка — core.autocrlf. По умолчанию false, что значит «не конвертировать окончания строк», но на Windows народ часто переключает в true:
```
$ git config core.autocrlf false
```

Выполнять нужно в конкретном репозитории. Если добавить флаг `--global`, эта настройка будет применятся вообще во всех твоих репозиториях.

Настройка конвертирует LF в CRLF при checkout и обратно при commit, т.е. в репозитории будут LF-окончания, а в твоей рабочей копии — CRLF.

2018-07-29 20:57 UTC, bopoh13 commented
@Minoru, к сожалению, данная настройка [не убирает BOM из файлов в UTF-8](https://github.com/desktop/desktop/issues/3768) после редактирования мной в Notepad (поэтому пришлось экспериментировать, чтобы не ломать исходную кодировку).

2018-07-29 21:00 UTC, bopoh13 commented
@Minoru, к сожалению, данная настройка сама по себе [не убирает BOM из файлов в UTF-8](https://github.com/desktop/desktop/issues/3768) после редактирования мной в Notepad (поэтому пришлось экспериментировать, чтобы не ломать исходную кодировку).

2018-07-29 21:02 UTC, bopoh13 commented
@Minoru, к сожалению, данная настройка сама по себе [не убирает BOM из файлов в UTF-8](https://github.com/desktop/desktop/issues/3768) после редактирования мной в Notepad (поэтому пришлось экспериментировать, чтобы не дописывать мусор в виде символом BOM или не ломать исходную кодировку).

2018-07-29 21:13 UTC, bopoh13 commented
@Minoru, в целом вы правы - настройка необходима. Но данная настройка после редактирования _мной_ текста в Notepad [не убирает BOM из файлов в UTF-8](https://github.com/desktop/desktop/issues/3768) (рекомендую пользователям Windows перед индексацией применять команду, чтобы не дописывать в файлы "мусор" в виде символов BOM).

2018-07-29 21:25 UTC, toby3d commented
Самый действенный совет это, конечно, не использовать Notepad вовсе и найти, наконец, нормальный текстовой редактор.

**P.S.:** Только не Word и не Wordpad, боже упаси...

2020-04-20 19:20 UTC, bopoh13 commented
https://github.com/NotDotTeam/trust/blob/4a99513ae46b72b9747812fb7e62535a09e480db/words.html#L593-L594
Джон Стюарт Милль воспринимал Иммануила Канта именно так (как последствия), но на мой взгляд это проверка на отсутствия психопата: у которого на первом плане всегда стоят личные желания и нужды, когда другой человек является средством (без уважения как к разумному существу, без признания достоинств, с манипуляциями и желанием управлять), а не целью.